-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 17:24:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema autoprevoznik
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autoprevoznik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoprevoznik` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `autoprevoznik` ;

-- -----------------------------------------------------
-- Table `autoprevoznik`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoprevoznik`.`roles` (
  `role_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `roles` (`role_name`) VALUES
('Anonymus'),
('Korisnik'),
('Kondukter'),
('Admin'),
('Superadmin');
-- -----------------------------------------------------
-- Table `autoprevoznik`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoprevoznik`.`users` (
  `user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_name` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `users_email` VARCHAR(255) NOT NULL,
  `users_phone` VARCHAR(15) NULL DEFAULT NULL,
  `total_reservations` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `total_not_showing` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  `date_added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `role_id` INT(10) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_roles1_idx` (`role_id` ASC) ,
  CONSTRAINT `fk_users_roles_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `autoprevoznik`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'telefon je opciono. broj nepojavljivanja je ogranicen kako bi se sprecile lazne rezervacije';

INSERT INTO `users` (`users_name`, `password_hash`, `users_email`, `users_phone`, `total_reservations`, `total_not_showing`, `date_added`, `role_id`) VALUES
('admin', '21232f297a57a5a743894a0e4a801fc3', 'admin@wbus.com', NULL, 0, 0, '2019-10-16 02:28:30', 4),
('super', '1b3231655cebb7a1f783eddf27d254ca', 'super@wbus.com', NULL, 0, 0, '2019-10-16 02:28:30', 5),
('kondukter', '43c2cfa8100f898efc7da515fe9a468a', 'kondukter@wbus.com', NULL, 0, 0, '2019-10-16 02:28:30', 3),
('user1', '24c9e15e52afc47c225b757e7bee1f9d', 'user1@gmail.com', NULL, 0, 0, '2019-10-16 02:28:30', 2),
('vozac', 'fe4644d75b0cb2fbbf9da6241e4919a0', 'vozac@wbus.com', NULL, 0, 0, '2019-10-16 02:28:30', 3),
('user2', '7e58d63b60197ceb55a1c487989a3720', 'user2@gmail.com', '0612345678', 0, 0, '2019-10-28 23:16:32', 2),
('kond2', '4da2f6eb7490686d175b2aeb94ea5da6', 'kond2@wbus.com', '', 0, 0, '2019-10-28 23:19:41', 2),
('user3', '92877af70a45fd6a2ed7fe81e1236b78', 'user3@gmail.com', '', 0, 0, '2019-10-28 23:20:29', 2),
('kond3', '23799f3875011b730040e6b72f5dbe2d', 'kond3@wbus.com', '061789465', 0, 0, '2019-10-29 03:46:26', 2),
('user4', '3f02ebe3d7929b091e3d8ccfde2f3bc6', 'user4@gmail.com', '', 0, 0, '2019-11-13 22:23:12', 2),
('kond4', '77355a5e673d317d60839529ae4939e1', 'kond4@wbus.com', '0617894645', 0, 0, '2019-11-14 04:05:51', 2);

-- -----------------------------------------------------
-- Table `autoprevoznik`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoprevoznik`.`employees` (
  `employee_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `working_place` INT(2) NOT NULL,
  `date_added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `date_edited` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `wage_per_hour` DOUBLE UNSIGNED NULL DEFAULT NULL,
  `available` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `conducter_id_UNIQUE` (`employee_id` ASC) ,
  INDEX `fk_conducters_users_user_id` USING BTREE (`user_id`) ,
  CONSTRAINT `fk_conducters_users_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `autoprevoznik`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'tabela svih zaposlenih';

INSERT INTO `employees` (`user_id`, `working_place`, `date_added`, `date_edited`, `wage_per_hour`, `available`) VALUES
(3, 2, '2019-10-16 02:22:12', '2019-11-17 06:44:20', NULL, 1),
(5, 1, '2019-10-16 02:22:12', '2019-11-17 06:44:20', NULL, 1);
-- -----------------------------------------------------
-- Table `autoprevoznik`.`timetables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoprevoznik`.`timetables` (
  `timetable_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `station_order` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `date_added` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`timetable_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO `timetables` (`station_order`, `date_added`) VALUES
('[[1,\"Beograd\",\"11\",\"15\",\"0\"],[2,\"Velika Plana\",\"12\",\"40\",\"92\"],[3,\"Donja Livadica\",\"12\",\"55\",\"106\"],[4,\"Porodin\",\"13\",\"00\",\"111\"],[5,\"Svilajnac\",\"13\",\"15\",\"122\"],[6,\"Grabovac\",\"13\",\"20\",\"126\"],[7,\"Sedlare\",\"13\",\"26\",\"131\"],[8,\"Jasenovo\",\"13\",\"34\",\"136\"],[9,\"Miliva\",\"13\",\"50\",\"146\"],[10,\"Despotovac\",\"13\",\"55\",\"149\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"06\",\"30\",\"0\"],[2,\"Kragujevac\",\"08\",\"30\",\"137\"],[3,\"Novi Pazar\",\"12\",\"15\",\"287\"]]', '2019-11-14'),
('[[1,\"Aleksinac\",\"20\",\"45\",\"205\"],[2,\"Nis\",\"21\",\"15\",\"236\"],[3,\"Prokuplje\",\"21\",\"55\",\"267\"],[4,\"Mala Plana\",\"22\",\"10\",\"277\"],[5,\"Blace\",\"22\",\"35\",\"296\"]]', '2019-11-14'),
('[[1,\"Velika Plana\",\"13\",\"35\",\"0\"],[2,\"Donja Livadica\",\"13\",\"42\",\"97\"],[3,\"Zabari\",\"13\",\"55\",\"106\"],[4,\"Porodin\",\"14\",\"01\",\"111\"],[5,\"Vitezevo\",\"14\",\"03\",\"113\"],[6,\"Svilajanc\",\"14\",\"15\",\"122\"],[7,\"Kragujevac\",\"15\",\"23\",\"165\"]]', '2019-11-14'),
('[[1,\"Sabac\",\"14\",\"00\",\"0\"],[2,\"Beograd\",\"15\",\"15\",\"120\"],[3,\"Subotica\",\"17\",\"11\",\"300\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"12\",\"12\",\"0\"],[2,\"Svilajnac\",\"13\",\"13\",\"13\"],[3,\"SMederevo\",\"15\",\"15\",\"15\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"12\",\"12\",\"12\"],[2,\"Svilajnac\",\"20\",\"20\",\"20\"],[3,\"Zlatibor\",\"21\",\"02\",\"1\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"12\",\"12\",\"12\"],[2,\"Svilajnac\",\"20\",\"20\",\"20\"],[3,\"Zlatibor\",\"21\",\"02\",\"1\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"20\",\"20\",\"20\"],[2,\"Novi Sad\",\"12\",\"12\",\"0\"],[3,\"Subotica\",\"16\",\"16\",\"16\"],[4,\"Sombor\",\"20\",\"20\",\"20\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"17\",\"17\",\"17\"],[2,\"Kragujevac\",\"20\",\"20\",\"20\"],[3,\"Zajecar\",\"21\",\"21\",\"21\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"13\",\"13\",\"13\"],[2,\"Uzice\",\"18\",\"18\",\"18\"],[3,\"Nova Varos\",\"19\",\"19\",\"19\"]]', '2019-11-14'),
('[[1,\"Smederevo\",\"16\",\"16\",\"16\"],[2,\"Beograd\",\"18\",\"18\",\"18\"],[3,\"Novi Sad\",\"19\",\"19\",\"19\"],[4,\"Subotica\",\"22\",\"22\",\"22\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"13\",\"13\",\"13\"],[2,\"Zrenjanin\",\"01\",\"01\",\"1\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"12\",\"12\",\"12\"],[2,\"Svilajnac\",\"14\",\"14\",\"14\"]]', '2019-11-14'),
('[[1,\"Beograd\",\"11\",\"11\",\"11\"],[2,\"Smederevo\",\"12\",\"12\",\"12\"],[3,\"Zajecar\",\"13\",\"13\",\"13\"]]', '2019-11-15');
-- -----------------------------------------------------
-- Table `autoprevoznik`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoprevoznik`.`reservations` (
  `reservation_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `timetable_id` INT(10) UNSIGNED NOT NULL,
  `users_name` VARCHAR(255) NULL DEFAULT NULL,
  `reserve_date` DATE NOT NULL,
  `enter_station` INT(255) NOT NULL,
  `exit_station` INT(255) NOT NULL,
  `number_of_seats` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1,
  `completed` TINYINT(2) NULL DEFAULT 0,
  `date_added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`reservation_id`),
  INDEX `fk_reservations_timetables1_idx` (`timetable_id` ASC) ,
  CONSTRAINT `fk_reservations_timetables1`
    FOREIGN KEY (`timetable_id`)
    REFERENCES `autoprevoznik`.`timetables` (`timetable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `autoprevoznik`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoprevoznik`.`tickets` (
  `tickets_id` INT(10) UNSIGNED NOT NULL,
  `conducter_id` INT(10) UNSIGNED NOT NULL,
  `timetable_id` INT(10) UNSIGNED NOT NULL,
  `ticket_date` DATE NOT NULL,
  `enter_station` INT(255) NOT NULL,
  `exit_station` INT(255) NOT NULL,
  `number_of_seats` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1,
  `completed` TINYINT(2) NULL DEFAULT 0,
  `date_added` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  INDEX `fk_tickets_timetables1_idx` (`timetable_id` ASC) ,
  CONSTRAINT `fk_tickets_timetables1`
    FOREIGN KEY (`timetable_id`)
    REFERENCES `autoprevoznik`.`timetables` (`timetable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `autoprevoznik`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoprevoznik`.`vehicles` (
  `vehicle_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `licence_plate` VARCHAR(10) NOT NULL,
  `max_capacity` TINYINT(3) UNSIGNED NOT NULL,
  `available` INT(1) NULL DEFAULT 1,
  PRIMARY KEY (`vehicle_id`),
  UNIQUE INDEX `licence_plate_UNIQUE` (`licence_plate` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'ceo vozni park... mini busevi, regularni autobusi, doubledecker-i';

INSERT INTO `vehicles` (`type`, `licence_plate`, `max_capacity`, `available`) VALUES
('minibus', 'BG123SV', 19, 1),
('regular', 'SV123KG', 52, 1),
('doubledecker', 'KG123BG', 80, 1);
-- -----------------------------------------------------
-- Table `autoprevoznik`.`warrants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autoprevoznik`.`warrants` (
  `warrant_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `warrant_date` DATE NOT NULL,
  `vehicle_id` INT(10) UNSIGNED NOT NULL,
  `timetable_id` INT(10) UNSIGNED NOT NULL,
  `driver_id` INT(10) UNSIGNED NOT NULL,
  `conducter_id` INT(10) UNSIGNED NOT NULL,
  `max_number_passengers` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `current_station` INT(11) NOT NULL DEFAULT 1,
  `finished` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`warrant_id`),
  INDEX `fk_warrants_drivers_driver_id` USING BTREE (`driver_id`) ,
  INDEX `fk_warrants_vehicles_vehicle_id` USING BTREE (`vehicle_id`) ,
  INDEX `fk_warrants_line_statistics_line_id` USING BTREE (`timetable_id`) ,
  INDEX `fk_warrants_conducters_conducter_id` USING BTREE (`conducter_id`) ,
  CONSTRAINT `fk_warrants_vehicles1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `autoprevoznik`.`vehicles` (`vehicle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warrants_employees1`
    FOREIGN KEY (`conducter_id`)
    REFERENCES `autoprevoznik`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warrants_timetables1`
    FOREIGN KEY (`timetable_id`)
    REFERENCES `autoprevoznik`.`timetables` (`timetable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3422
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'privremena tabela koja kao ime ima datum i koja se kreira unapred neko vreme, a brise kada od datog datuma prodje unapred zadato vreme\\\\\\\\n\\\\\\\\nSadrzi sve radne naloge tog dana';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
